version: 2
# Build documentation in the docs/ directory with Sphinx
sphinx:
   configuration: docs/conf.py

conda:
  environment: environment.yml
python:
  install:
    - extra_requirements: docs/requirements.txt
 