site_name: FPGA_Projectmain
site_url: https://github.com/jomidokunMain/FPGA_Projectmain.git
nav:
    - Home: /home/jesudara/Desktop/FPGA_Project/FPGA_Projectmain/index.md
    - About: /home/jesudara/Desktop/FPGA_Project/FPGA_Projectmain/about.md


theme: readthedocs