set_property SRC_FILE_INFO {cfile:/home/jesudara/Desktop/FPGA_projects/Vivdao/project_2/project_2.srcs/constrs_1/new/swledconstraint.xdc rfile:../../../project_2.srcs/constrs_1/new/swledconstraint.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T1 [get_ports SW]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L1 [get_ports LED]
