set_property SRC_FILE_INFO {cfile:/home/jesudara/Desktop/FPGA_projects/Vivdao/data_selector_verilog/data_selector_verilog.srcs/constrs_1/new/data_selcon.xdc rfile:../../../data_selector_verilog.srcs/constrs_1/new/data_selcon.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R2 [get_ports A]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T1 [get_ports B]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U1 [get_ports SEL]
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W3 [get_ports Q]
